trigger:
- main

resources:
- repo: self

variables:
  imageRepo: sampleapp
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Newone'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'
    - task: HelmDeploy@0
      displayName: Helm install
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'Free Trial (e2fba2b7-9a10-4a10-8a17-720c878b8e00)'
        azureResourceGroup: 'group-resource'
        kubernetesCluster: 'webappcluster'
        useClusterAdmin: true
        namespace: 'default'
        command: 'install'
        chartType: 'FilePath'
        chartPath: 'Application/charts/sampleapp'
    - task: HelmDeploy@0
      displayName: Helm package
      inputs:
        command: 'package'
        chartPath: 'Application/charts/sampleapp'
        destination: '$(Build.ArtifactStagingDirectory)Application/charts/sampleapp'
        
- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        targetPath: '$(Pipeline.Workspace)/manifests'
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'NewAKS'
        namespace: 'default'
        manifests: |
          $(Pipeline.Workspace)/manifests/deployment.yml
          $(Pipeline.Workspace)/manifests/service.yml
